#!/usr/bin/env bash
# E2E test: clawvisor-server install on a totally fresh machine.
#
# Runs inside a fresh Docker container with no prior state. The binary is
# placed on PATH to simulate a user who already has it (e.g. via a package
# manager or manual download), then `clawvisor-server install` drives the full
# setup wizard and service installation.
set -euo pipefail
source "$HOME/assertions.sh"

# Non-interactive setup env vars.
export CLAWVISOR_NON_INTERACTIVE=1
export CLAWVISOR_LLM_PROVIDER=openai
export CLAWVISOR_LLM_ENDPOINT=http://localhost:9999
export CLAWVISOR_LLM_MODEL=gpt-4o-mini
export CLAWVISOR_LLM_API_KEY=sk-fake-e2e-test-key
export CLAWVISOR_TELEMETRY=false
export CLAWVISOR_CHAIN_CONTEXT=true
export CLAWVISOR_RELAY_URL=wss://localhost:9998

DATA_DIR="$HOME/.clawvisor"

# Put the binary on PATH, simulating a user who downloaded it manually.
export PATH="$HOME/.e2e-bin:$PATH"

echo ""
echo "═══ E2E: clawvisor-server install (fresh machine) ═══"
echo ""

# ── 1. Pre-flight: truly nothing exists ──────────────────────────────────────
echo "── 1. Pre-flight"

if [ ! -d "$DATA_DIR" ]; then
  pass "no ~/.clawvisor dir"
else
  fail "~/.clawvisor already exists"
fi

if [ ! -f "$HOME/.config/systemd/user/clawvisor.service" ]; then
  pass "no systemd unit"
else
  fail "systemd unit already exists"
fi

clawvisor-server --help >/dev/null 2>&1
pass "binary runs"

# ── 2. clawvisor-server install — full wizard + service install ─────────────────────
echo ""
echo "── 2. clawvisor-server install"

# The wizard runs the full setup: generates config, keys, JWT secret, starts
# a temporary server, creates admin user, writes .local-session, then writes
# the systemd unit. systemctl will fail in Docker (no init) — that's expected.
INSTALL_OUTPUT=$(clawvisor-server install 2>&1 || true)
echo "$INSTALL_OUTPUT"

# ── 3. Setup wizard artifacts ────────────────────────────────────────────────
echo ""
echo "── 3. Wizard artifacts"

assert_dir_exists "$DATA_DIR" "data dir created"
assert_dir_exists "$DATA_DIR/logs" "logs dir created"

# Config generated by the wizard (not pre-seeded).
assert_file_exists "$DATA_DIR/config.yaml" "config.yaml generated"
assert_file_mode "$DATA_DIR/config.yaml" "600" "config.yaml permissions"
assert_file_contains "$DATA_DIR/config.yaml" "port: 25297" "config port"
assert_file_contains "$DATA_DIR/config.yaml" "driver: \"sqlite\"" "config sqlite"
assert_file_contains "$DATA_DIR/config.yaml" "provider: openai" "config LLM provider"
assert_file_contains "$DATA_DIR/config.yaml" "model: gpt-4o-mini" "config LLM model"
assert_file_contains "$DATA_DIR/config.yaml" "sk-fake-e2e-test-key" "config API key"

# Cryptographic keys.
assert_file_exists "$DATA_DIR/vault.key" "vault key"
assert_file_not_empty "$DATA_DIR/vault.key" "vault key not empty"
assert_file_mode "$DATA_DIR/vault.key" "600" "vault key permissions"

assert_file_exists "$DATA_DIR/daemon-ed25519.key" "Ed25519 key"
assert_file_not_empty "$DATA_DIR/daemon-ed25519.key" "Ed25519 key not empty"

assert_file_exists "$DATA_DIR/daemon-x25519.key" "X25519 key"
assert_file_not_empty "$DATA_DIR/daemon-x25519.key" "X25519 key not empty"

# Server created admin user and wrote local session during setup.
assert_file_exists "$DATA_DIR/.local-session" "local session"

# ── 4. Systemd unit ──────────────────────────────────────────────────────────
echo ""
echo "── 4. Systemd unit"

UNIT_FILE="$HOME/.config/systemd/user/clawvisor.service"

assert_file_exists "$UNIT_FILE" "unit file created"
assert_file_contains "$UNIT_FILE" "ExecStart=" "ExecStart"
assert_file_contains "$UNIT_FILE" "start --foreground" "foreground flag"
assert_file_contains "$UNIT_FILE" "CONFIG_FILE=" "CONFIG_FILE env"
assert_file_contains "$UNIT_FILE" "Restart=always" "restart policy"

# ── 5. Start daemon + health check ──────────────────────────────────────────
echo ""
echo "── 5. Health check"

DAEMON_LOG="$HOME/.daemon-output.log"
clawvisor-server start --foreground >"$DAEMON_LOG" 2>&1 &
DAEMON_PID=$!

HEALTHY=false
for i in $(seq 1 30); do
  if curl -sf http://127.0.0.1:25297/health >/dev/null 2>&1; then
    HEALTHY=true
    break
  fi
  sleep 0.5
done

if $HEALTHY; then
  pass "health check"
else
  fail "daemon not healthy within 15s"
fi

if $HEALTHY; then
  BODY=$(curl -sf http://127.0.0.1:25297/health 2>/dev/null || echo "{}")
  if echo "$BODY" | grep -q '"status"'; then
    pass "health JSON"
  else
    fail "unexpected health body: $BODY"
  fi
fi

assert_file_exists "$DATA_DIR/clawvisor.db" "SQLite database"

# ── 6. Local session token opens dashboard (not login page) ──────────────────
echo ""
echo "── 6. Dashboard auth"

if $HEALTHY; then
  assert_dashboard_auth_works "$DAEMON_LOG"
else
  fail "skipped dashboard auth test (daemon not healthy)"
fi

kill "$DAEMON_PID" 2>/dev/null || true
wait "$DAEMON_PID" 2>/dev/null || true
pass "daemon stopped"

# ── 7. Uninstall ─────────────────────────────────────────────────────────────
echo ""
echo "── 6. Uninstall"

clawvisor-server uninstall 2>/dev/null || true

if [ ! -f "$UNIT_FILE" ]; then
  pass "unit removed"
else
  fail "unit still exists"
fi

print_results
